package com.board.bong.contorller;

import com.board.bong.bean.User;
import com.board.bong.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;

@RestController
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path = "/login/signUp")
    public void singUp(@RequestBody SignUpParam signUpParam) {
        String idForEncode = "bcrypt";
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        User user = new User();
        try {
            user.setId(signUpParam.id);
            user.setPassword("{" + idForEncode + "}" + encoder.encode(signUpParam.password));
            user.setRole("USER");
            userRepository.save(user);
        } catch (Exception e) {
            e.printStackTrace();
        }
    };

    public static class SignUpParam { // implements Serializable {
        public String id;
        public String password;
    }
}

